In [18]:
# importing Required library 

from selenium import webdriver
import pandas as pd
from bs4 import BeautifulSoup
from time import sleep
import time
from datetime import date

driver=webdriver.Edge(r"C:\Users\PANKAJ\Downloads\msedgedriver.exe")
driver.get("https://in.indeed.com/jobs?q=Data+Scientist&l=Delhi")
# finding the details which are scraped from the web server
jobtitle = []
company = []
location = []
daysposted = []
salary = []
description = []
crawl_timestamp = []
crawl_date = []

In [20]:
jobs = driver.find_elements_by_class_name('result')
# lets scrap the data from the server with the help of for loop
for job in jobs:
    
    res= job.get_attribute('innerHTML')
    jb = BeautifulSoup(res,'html.parser')

    try:
        title = jb.find("a" ,class_="jobtitle").text.replace('\n',' ')
        jobtitle.append(title)
    except:
        jobtitle.append('  ')
 
    try:
        com= jb.find("span" ,class_="company").text.replace('\n',' ')
        company.append(com)
    except:
        company.append(' ')

    try:
        lo = jb.find("span" ,class_="location accessible-contrast-color-location").text.replace('\n',' ')
        location.append(lo)
    except:
        location.append(' ')      
      
    try:
        sal = jb.find("span" ,class_="salaryText").text.replace('\n',' ')
        salary.append(sal)
    except:
        salary.append('Not Mentioned')
       
    try:
        day = jb.find("span" ,class_="date").text.replace('\n',' ')
        daysposted.append(day)
    except:
        daysposted.append(' ')
     
    try:
        jo = jb.find("div" ,class_="summary").text.replace('\n',' ')
        description.append(jo)
    except:
        description.append('----')
# lets scrap the date time form the server with the help of loop            
    time.sleep(2)
            
    task1 = time.gmtime()
    crawl_timestamp.append(time.strftime("%Y-%m-%d %H:%M:%S", task1))

    today = date.today()    
    task2 = today.strftime("%d %B %Y")
    crawl_date.append(task2)

In [21]:
# lets finding the leangth of the scraped attributes so that we can create the dataframe of the result 
print(len(jobtitle),len(company),len(location),len(daysposted),len(salary),len(description),len(crawl_timestamp),len(crawl_date))

15 15 15 15 15 15 15 15

In [22]:
# lets create the indeed data table
indeed =pd.DataFrame({ 'Job Name' : jobtitle ,'Job Location' : location,'Company Name' : company ,' Salary' :salary ,'Post Days' : daysposted ,'Time': crawl_timestamp , ' Date' : crawl_date ,'Job Description' : description  })
indeed

,Job Name,Job Location,Company Name,Salary,Post Days,Time,Date,Job Description
0,Data Scientist,"New Delhi, Delhi",Terra Economics & Analytics Lab (TEAL),Not Mentioned,30+ days ago,2020-12-31 15:38:19,31 December 2020,Creating compelling data visualizations and ...
1,Data Scientist,"Delhi, Delhi",AI Engineer,"₹17,000 - ₹25,000 a month",28 days ago,2020-12-31 15:38:21,31 December 2020,Ability to use data visualization tools to s...
2,Data Scientist,"Delhi, Delhi",NatWest Group,Not Mentioned,30+ days ago,2020-12-31 15:38:23,31 December 2020,This is an opportunity to participate in the...
3,Machine Learning Engineer,"Delhi, Delhi",VNU SOFTWARE Pvt Ltd.,"₹25,000 - ₹40,000 a month",30+ days ago,2020-12-31 15:38:25,31 December 2020,We are looking for experience Machine Learni...
4,Data Analytics Internship,"Delhi, Delhi",Tsukiindia,"₹4,000 a month",6 days ago,2020-12-31 15:38:27,31 December 2020,Working as a data analyst and mining data 2....
5,Data Scientist,"Delhi, Delhi",Team Computers,Not Mentioned,2 days ago,2020-12-31 15:38:29,31 December 2020,Extraction of actionable data from unstructu...
6,Data Scientist,Delhi,RGF Professional Recruitment,Not Mentioned,30+ days ago,2020-12-31 15:38:31,31 December 2020,Looking for Data Scientist with one of the l...
7,Machine Learning (ML)/Natural Language Proces...,"New Delhi, Delhi",Pointers Digitech Pvt Ltd.,"₹4,00,000 - ₹5,00,000 a year",2 days ago,2020-12-31 15:38:33,31 December 2020,Supervising the data acquisition process if ...
8,DATA SCIENTIST,"Delhi, Delhi",Innefu Labs Pvt. Ltd.,Not Mentioned,30+ days ago,2020-12-31 15:38:35,31 December 2020,Keep up-to-date with latest technology trend...
9,Data Scientist,"Defence Colony, Delhi, Delhi",Mahajan Imaging,Not Mentioned,30+ days ago,2020-12-31 15:38:37,31 December 2020,Responsible for driving Mahajan Imaging's ne...
10,Data Scientist,"New Delhi, Delhi",Ank Aha,Not Mentioned,30+ days ago,2020-12-31 15:38:39,31 December 2020,Ensure data integrity and consistency across...
11,Manager Data Scientist,"Delhi, Delhi",Innefu Labs Pvt. Ltd.,Not Mentioned,30+ days ago,2020-12-31 15:38:41,31 December 2020,Must be able to handle deployment complexiti...
12,Data Scientist,"New Delhi, Delhi",Sentieo,Not Mentioned,30+ days ago,2020-12-31 15:38:43,31 December 2020,Comfortable with data visualization tools li...
13,Sr.Data Scientist,"Delhi, Delhi",Innefu Labs Pvt. Ltd.,Not Mentioned,30+ days ago,2020-12-31 15:38:45,31 December 2020,Must be able to handle deployment complexiti...
14,Machine Learning Internship,"Delhi, Delhi",TestRight Nanosystems,"₹10,000 a month",11 days ago,2020-12-31 15:38:47,31 December 2020,How would you know if that jacket is genuine...