In [1]:
# Importing the Libraries
import pandas as pd
import selenium
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
import time
start_page=0
end_page=8
#Loading Driver
driver=webdriver.Edge(r"C:\Users\PANKAJ\Downloads\msedgedriver.exe")
# Giving the name of the website which we have to scrap
url="https://in.indeed.com/jobs?q=data+scientist&l=delhi"
# Getting the URL
driver.get(url)
# we have to scrap the below attached details
Job_Name=[]
Job_Location=[]
Company_Name=[]
Salary=[]
Job_Desc=[]
Post_Days=[]
Exp_Years=[]
# now lets scrap the data from the server            
name=driver.find_elements_by_xpath("//h2[@class='title']")
for n in name:
    j_name=n.text
    Job_Name.append(j_name)
    JN=pd.DataFrame(Job_Name)
    JN=JN.rename({0: 'Job Name'},axis=1)
location=driver.find_elements_by_xpath("//span[@class='location accessible-contrast-color-location']")
for ln in location:
    ln_name=ln.text
    Job_Location.append(ln_name)
    LN=pd.DataFrame(Job_Location)
    LN=LN.rename({0: 'Job Location'},axis=1)
company=driver.find_elements_by_xpath("//div[@class='sjcl']/div[1]")
for co in company:
    co_name=co.text
    Company_Name.append(co_name)
    CN=pd.DataFrame(Company_Name)
    CN=CN.rename({0: 'Company Name'},axis=1)
salary=driver.find_elements_by_xpath("//span[@class='salary no-wrap']")
for s in salary:
    s_amt=s.text
    Salary.append(s_amt)
    S=pd.DataFrame(Salary)
    S=S.rename({0: 'Salary P/M/Y'},axis=1)
desc=driver.find_elements_by_xpath("//div[@class='summary']")
for d in desc:
    d_short=d.text
    Job_Desc.append(d_short)
    JD=pd.DataFrame(Job_Desc)
    JD=JD.rename({0: 'Job Description'},axis=1)
postday=driver.find_elements_by_xpath("//span[@class='date ']")
for p in postday:
    post=p.text
    Post_Days.append(post)
    PD=pd.DataFrame(Post_Days)
    PD=PD.rename({0: 'Post Days'},axis=1)
    
# now lets create the data table and adding the columns into the table
indeed=pd.concat([JN,LN,CN,S,JD,PD],axis=1)
indeed

,Job Name,Job Location,Company Name,Salary P/M/Y,Job Description,Post Days
0,Data Scientist,"Delhi, Delhi",AI Engineer,"₹17,000 - ₹25,000 a month",Ability to use data visualization tools to sho...,17 days ago
1,Data Analytics Internship\nnew,"Delhi, Delhi",TBM Technologies Private Limited,"₹5,000 a month",Developing BI reports and charts based on mach...,3 days ago
2,Data Scientist,"New Delhi, Delhi",Terra Economics & Analytics Lab (TEAL),"₹4,00,000 - ₹8,00,000 a year",Creating compelling data visualizations and co...,30+ days ago
3,Data Scientist,"New Delhi, Delhi",Profile Enterprises Ltd,"₹10,000 a month",Develop custom data models and algorithms to a...,18 days ago
4,Machine Learning Internship\nnew,"Delhi, Delhi",TestRight Nanosystems,"₹2,500 - ₹5,000 a month",How would you know if that jacket is genuine l...,Today
5,Machine Learning part time job/internship at D...,"Delhi, Delhi",Sarvvid AI,"₹30,000 - ₹45,000 a month",Sarvvid-AI has the vision to create a smarter ...,3 days ago
6,Data Scientist,Delhi,RGF Professional Recruitment,"₹2,000 a month",Looking for Data Scientist with one of the lea...,30+ days ago
7,Data Scientist with experience in customer dat...,"Delhi, Delhi",ifood web media technologies,"₹6,000 a month","Responsible for identifying data requirements,...",30+ days ago
8,Data Scientist,"Defence Colony, Delhi, Delhi",Mahajan Imaging,NaN,Responsible for driving Mahajan Imaging's new ...,30+ days ago
9,DATA SCIENTIST,"Delhi, Delhi",Innefu Labs Pvt. Ltd. 3.5,NaN,Keep up-to-date with latest technology trends....,30+ days ago
10,Data Analytics Internship,"Delhi, Delhi",Accord Innovations Private Limited,NaN,Analytical and logical skills Knowledge or exp...,9 days ago
11,Manager Data Scientist,"Delhi, Delhi",Innefu Labs Pvt. Ltd. 3.5,NaN,Must be able to handle deployment complexities...,30+ days ago
12,Sr.Data Scientist,"Delhi, Delhi",Innefu Labs Pvt. Ltd. 3.5,NaN,Must be able to handle deployment complexities...,30+ days ago
13,Data Scientist,"New Delhi, Delhi",Sentieo,NaN,Comfortable with data visualization tools like...,30+ days ago
14,Big Data part time job/internship at Delhi,"Delhi, Delhi",Rit Learning Fields Private Limited,NaN,Working on user interaction and data mining.\n...,9 days ago